//. PROGRAM TO READ MARKS OF FIVE SUBJECT AND PRINT DIVISION.
#include<stdio.h>
int main(){
    //TAKING MARKS OF THE 5 SUBJECTS FROM STUDENTS
int a,b,c,d,e;
printf("ENTER MARKS OF FIVE SUBJECTS");
scanf("%d%d%d%d%d",&a,&b,&c,&d,&e);
//DIVIDING STUDENTS IN DIVISION ON THE BASIS OF PERFORMANCES 
if((a+b+c+d+e/500)*100>=80)//A DIVISION FOR STUDENTS GETTING MORE THAN 80% 
{
printf("FIRST DIVISION");}
else if((a+b+c+d+e/500)*100>=60)//B DIVISION FOR STUDENTS GETTING MORE THAN 60% 
{
printf("SECOND DIVISION");
} 
else
printf("THIRD DIVISION");//C DIVISION FOR STUDENTS GETTING LESS THAN 60% 

return 0;
}
